package com.e8Security.cloudChamber.whois.parser;

/***
 * ParsingPattern enum is used for parsing different patterns.
 * 
 * @author Abhijit
 *
 */
enum ParsingPattern {

	  WHOIS_NETRANGE_PATTERN
,	  WHOIS_ORIGINASN_PATTERN
,	  WHOIS_NETNAME_PATTERN
,	  WHOIS_NETHANDLE_PATTERN
,	  WHOIS_PARENT_PATTERN
,	  WHOIS_NETTYPE_PATTERN
,	  WHOIS_REGDATE_PATTERN
,	  WHOIS_UPDATEDATE_PATTERN
,	  WHOIS_REF_PATTERN
,	  WHOIS_ORGNAME_PATTERN
,	  WHOIS_ORGID_PATTERN
,	  WHOIS_ORGADDRESS_PATTERN
,	  WHOIS_ORGCITY_PATTERN
,	  WHOIS_ORGSTATE_PATTERN
,	  WHOIS_ORGPOSTAL_PATTERN
,	  WHOIS_ORGCOUNTRY_PATTERN
,	  WHOIS_ORGREGDATE_PATTERN
,	  WHOIS_ORGUPDATEDDATE_PATTERN
,	  WHOIS_ORGREF_PATTERN
,	  WHOIS_ORGTECHHANDLE_PATTERN
,	  WHOIS_ORGTECHNAME_PATTERN
,	  WHOIS_ORGTECHPHONE_PATTERN
,	  WHOIS_ORGTECHEMAIL_PATTERN
,	  WHOIS_ORGTECHREF_PATTERN
,	  WHOIS_ORGTECHFAX_PATTERN
,	  WHOIS_ORGTECHADDRESS_PATTERN
,	  WHOIS_ORGTECHREGDATE_PATTERN
,	  WHOIS_ORGTECHUPDATEDDATE_PATTERN
,	  WHOIS_ORGABUSEHANDLE_PATTERN
,	  WHOIS_ORGABUSENAME_PATTERN
,	  WHOIS_ORGABUSEPHONE_PATTERN
,	  WHOIS_ORGABUSEEMAIL_PATTERN
,	  WHOIS_ORGABUSEREF_PATTERN
,     WHOIS_ORGABUSEADDRESS_PATTERN
,	  WHOIS_ORGABUSEREGDATE_PATTERN
,	  WHOIS_ORGABUSEUPDATEDDATE_PATTERN
,	  WHOIS_ORGADMINHANDLE_PATTERN
,	  WHOIS_ORGADMINNAME_PATTERN
,	  WHOIS_ORGADMINPHONE_PATTERN
,	  WHOIS_ORGADMINEMAIL_PATTERN
,	  WHOIS_ORGADMINFAX_PATTERN
,	  WHOIS_ORGADMINREF_PATTERN
,     WHOIS_ORGADMINADDRESS_PATTERN
,	  WHOIS_ORGADMINREGDATE_PATTERN
,	  WHOIS_ORGADMINUPDATEDDATE_PATTERN
,	  WHOIS_DATASOURCE_PATTERN
,     WHOIS_ORGPHONE_PATTERN
,     WHOIS_ORGFAX_PATTERN
,     WHOIS_DESCR_PATTERN
,	  WHOIS_ADMIN_PATTERN
,     WHOIS_ABUSE_PATTERN
,     WHOIS_TECH_PATTERN
,     WHOIS_NOC_PATTERN ;
	  
private ParsingPattern(){
		  
	  }
}
