package org.e8.whois.parser;

enum ParsingPattern {

	  WHOIS_NETRANGE_PATTERN
,	  WHOIS_ORIGINASN_PATTERN
,	  WHOIS_NETNAME_PATTERN
,	  WHOIS_NETHANDLE_PATTERN
,	  WHOIS_PARENT_PATTERN
,	  WHOIS_NETTYPE_PATTERN
,	  WHOIS_REGDATE_PATTERN
,	  WHOIS_UPDATEDATE_PATTERN
,	  WHOIS_REF_PATTERN
,	  WHOIS_ORGNAME_PATTERN
,	  WHOIS_ORGID_PATTERN
,	  WHOIS_ORGADDRESS_PATTERN
,	  WHOIS_ORGCITY_PATTERN
,	  WHOIS_ORGSTATE_PATTERN
,	  WHOIS_ORGPOSTAL_PATTERN
,	  WHOIS_ORGCOUNTRY_PATTERN
,	  WHOIS_ORGTECHHANDLE_PATTERN
,	  WHOIS_ORGTECHNAME_PATTERN
,	  WHOIS_ORGTECHPHONE_PATTERN
,	  WHOIS_ORGTECHEMAIL_PATTERN
,	  WHOIS_ORGTECHREF_PATTERN
,	  WHOIS_ORGABUSEHANDLE_PATTERN
,	  WHOIS_ORGABUSENAME_PATTERN
,	  WHOIS_ORGABUSEPHONE_PATTERN
,	  WHOIS_ORGABUSEEMAIL_PATTERN
,	  WHOIS_ORGABUSEREF_PATTERN
,	  WHOIS_DATASOURCE_PATTERN
,     WHOIS_ORGPHONE_PATTERN
,     WHOIS_ORGFAX_PATTERN
,     WHOIS_DESCR_PATTERN
,     WHOIS_ORGTECHADDRESS_PATTERN 
,     WHOIS_ORGABUSEADDRESS_PATTERN;
	  
private ParsingPattern(){
		  
	  }
}
